version: '3.5'
services:
  switcheolytics_flask:
    build:
      context: ""
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - ENV=development
      - PORT=8080
networks:
  default:
    name: switcheolytics_flask
